# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      otel_version:
        description: 'OpenTelemetry-cpp version to build. See https://github.com/open-telemetry/opentelemetry-cpp/releases/latest'
        default: 'v1.0.1'
        required: true

jobs:
  GetOpenTelemetryCpp:
    runs-on: windows-latest

    steps:
    - name: Download
      run: wget https://github.com/open-telemetry/opentelemetry-cpp/archive/refs/tags/${{ github.event.inputs.otel_version }}.zip
